get_living_codes <- function() {
    tibble::tribble(
        ~Code , ~Description                                                                                                                    , ~ExitCategory                  ,
        116L  , "Place not meant for habitation (e.g., a vehicle, an abandoned building, bus/train/subway station/airport or anywhere outside)" , "Homeless"                     ,
        101L  , "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, Host Home shelter"                        , "Homeless"                     ,
        101L  , "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, or RHY-funded Host Home shelter"          , "Homeless"                     ,
        118L  , "Safe Haven"                                                                                                                    , "Homeless"                     ,
        215L  , "Foster care home or foster care group home"                                                                                    , "Institutional"                ,
        215L  , "Permanent housing (other than RRH) for formerly homeless persons"                                                              , "Institutional"                ,
        206L  , "Hospital or other residential non-psychiatric medical facility"                                                                , "Institutional"                ,
        207L  , "Jail, prison or juvenile detention facility"                                                                                   , "Institutional"                ,
        225L  , "Long-term care facility or nursing home"                                                                                       , "Institutional"                ,
        204L  , "Psychiatric hospital or other psychiatric facility"                                                                            , "Institutional"                ,
        205L  , "Substance abuse treatment facility or detox center"                                                                            , "Institutional"                ,
        205L  , "Substance abuse treatment facility or deto center"                                                                             , "Institutional"                ,
        302L  , "Transitional housing for homeless persons (including homeless youth)"                                                          , "Temporary"                    ,
        329L  , "Residential project or halfway house with no homeless criteria"                                                                , "Temporary"                    ,
        314L  , "Hotel or motel paid for without emergency shelter voucher"                                                                     , "Temporary"                    ,
        332L  , "Host Home (non-crisis)"                                                                                                        , "Temporary"                    ,
        312L  , "Staying or living with family, temporary tenure (e.g. room, apartment or house)"                                               , "Temporary"                    ,
        313L  , "Staying or living with friends, temporary tenure (e.g. room apartment or house)"                                               , "Temporary"                    ,
        327L  , "Moved from one HOPWA funded project to HOPWA TH"                                                                               , "Temporary"                    ,
        336L  , "Staying or living in a friend's room, apartment, or house"                                                                     , "Temporary"                    ,
        336L  , "Staying or living in a friend’s room, apartment or house"                                                                      , "Temporary"                    ,
        335L  , "Staying or living in a family member's room, apartment, or house"                                                              , "Temporary"                    ,
        335L  , "Staying or living in a family member’s room, apartment or house"                                                               , "Temporary"                    ,
        422L  , "Staying or living with family, permanent tenure"                                                                               , "Permanent"                    ,
        423L  , "Staying or living with friends, permanent tenure"                                                                              , "Permanent"                    ,
        426L  , "Moved from one HOPWA funded project to HOPWA PH"                                                                               , "Permanent"                    ,
        410L  , "Rental by client, no ongoing housing subsidy"                                                                                  , "Permanent"                    ,
        435L  , "Rental by client, with ongoing housing subsidy"                                                                                , "Permanent"                    ,
        435L  , "Rental by client in a public housing unit"                                                                                     , "Permanent"                    ,
        435L  , "Rental by client, with GPD TIP housing subsidy"                                                                                , "Permanent"                    ,
        435L  , "Rental by client, with HCV voucher (tenant or project based)"                                                                  , "Permanent"                    ,
        435L  , "Rental by client, with RRH or equivalent subsidy"                                                                              , "Permanent"                    ,
        435L  , "Rental by client, with VASH housing subsidy"                                                                                   , "Permanent"                    ,
        435L  , "Rental by client, with other ongoing housing subsidy"                                                                          , "Permanent"                    ,
        421L  , "Owned by client, with ongoing housing subsidy"                                                                                 , "Permanent"                    ,
        411L  , "Owned by client, no ongoing housing subsidy"                                                                                   , "Permanent"                    ,
         30L  , "No exit interview completed"                                                                                                   , "Data not collected"           ,
         17L  , "Other"                                                                                                                         , "Other"                        ,
         24L  , "Deceased"                                                                                                                      , "Other"                        ,
         37L  , "Worker unable to determine"                                                                                                    , "Client doesn't know"          ,
          8L  , "Client doesn't know"                                                                                                           , "Client doesn't know"          ,
          9L  , "Client prefers not to answer"                                                                                                  , "Client prefers not to answer" ,
         99L  , "Data not collected"                                                                                                            , "Data not collected"
    )
}
